config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :comics do
      post 'add_to_collection', on: :member
      get 'login'
    end

    member do
      get 'discover', to: 'comics#discover', as: 'user_discover_comics'
    end

    resources :comics, only: %i[index show new create] do
      member do
        post 'add_to_collection'
      end
    end
  end

  post 'comics/:id/add_to_collection', to: 'comics#add_to_collection', as: 'add_to_collection_comic'

  post '/discover/search', to: 'comics#search', as: 'search_comics_post'
  get '/login', to: 'users#login_form'
  post '/login', to: 'users#login_user'
  match '/logout', to: 'users#logout_user', via: %i[get post], as: 'logout'
  get '/register', to: 'users#new'
  post '/welcome', to: 'welcome#index'
  get '/', to: 'welcome#index'
  get '/dashboard', to: 'users#show'
  post '/dashboard/search', to: 'dashboard#search', as: 'dashboard_search'

  get '/users/:id/discover/comics', to: 'comics#discover', as: 'user_discover_comics'
  get '/users/:id/discover/search', to: 'comics#search', as: 'user_dashboard_search'
  get '/users/:id/comics', to: 'comics#index'
end

app/models/action_figure.rb
class ActionFigure < ApplicationRecord
  belongs_to :user

  validates_presence_of :figure
  validates_presence_of :brand
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user
  has_many :user_comics
  has_many :users, through: :user_comics

  attribute :comic_vine_id, :string
  attribute :site_detail_url, :string
  attribute :resource_type, :string
  attribute :store_date, :date
  attribute :image_url, :string
  attribute :volume, :string
  attribute :issue, :string
  attribute :title, :string

  validates_presence_of :title
  validates_presence_of :issue
  validates_presence_of :publisher

  #serialize :image, JSON

  def image_url
    image['medium_url'] if image.present?
  end

  def self.search(query)
    if query.present?
      where('title LIKE ?', "%#{query}%")
    else
      all
    end
  end
end

app/models/manga.rb
class Manga < ApplicationRecord
  belongs_to :user

  validates_presence_of :title
  validates_presence_of :issue
  validates_presence_of :publisher
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_comics
  has_many :comics, through: :user_comics

  has_many :action_figures
  has_many :manga

  validates_presence_of :username
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :password, presence: true, confirmation: true, on: :create
  validates_presence_of :password_confirmation, presence: true

  has_secure_password
end

app/models/user_comic.rb
class UserComic < ApplicationRecord
  belongs_to :user
  belongs_to :comic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :current_user
  def logged_in?
    session[:user_id].present?
  end
    def error_message(errors)
    errors.details.keys.map do |field|
      errors.full_messages_for(field).first
    end.join(", ") 
  end

  def current_user
 
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    puts "Current User: #{@current_user}"
    @current_user
  end

end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  include Rails.application.routes.url_helpers
  def index
    @comics = Comic.all
  end

  def search
    @user = current_user
    @comics = ComicsFacade.new(@user.id, params[:query]).comics
    @comics.each { |comic| comic.id ||= SecureRandom.uuid }
    render 'index'
  end

  def add_to_collection
    @user = User.find(params[:user_id])
    @comic = Comic.find(params[:id])

    if @user && @comic
      @user.comics << @comic
      redirect_to user_comics_path(@user), notice: 'Comic added to your collection'
    else
      redirect_to comics_path, alert: 'Comic not found'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome, #{@user.username}"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Error: #{error_message(@user.errors)}"
      redirect_to '/register'
    end
  end

  def show
    @facade = ComicsFacade.new(params[:id], params[:query])
    if logged_in?
      @user = User.find_by(params[:id])
      if @user.nil?
        flash[:alert] = 'Error: User not found'
        redirect_to '/'
      end
    else
      flash[:alert] = 'Error: You must be logged in or registered to access my dashboard'
      redirect_to '/'
    end
  end

  def login_user
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      puts "User ID in session: #{session[:user_id]}"
      redirect_to '/dashboard'
    else
      flash[:alert] = 'Incorrect Email or Password'
      redirect_to '/login'
    end
  end

  def logout_user
    reset_session
    redirect_to '/'
  end

  # def add_to_collection
  #   @comic = Comic.find_by(id: params[:id])
  #   if @comic
  #     @user = current_user
  #     @user.comics << @comic
  #     redirect_to '/comics', notice: 'Comic added to your collection'
  #   else
  #     redirect_to '/comics', alert: 'Comic not found'
  #   end
  # end

  private

  def user_params
    params.permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
   @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comics/discover.html.erb
<h1>Discover Comics</h1>

<center>
  <h2>Discover Comics</h2>
  <br><br>
  <%= button_to "Discover Comics", user_comics_path(@facade.user_id), method: :post %>
  <br>
  <%= form_with url: user_comics_path(@facade.user_id), method: :post, local: true do |form| %>
    <%= form.text_field :query, placeholder: "Search Comics" %>
    <%= form.submit 'Find Comics' %>
  <% end %>
</center>

app/views/comics/index.html.erb
<h2>Search Comics</h2>
<%= form_with url: search_comics_post_path, method: :post, local: true do |form| %>
  <%= form.text_field :query, placeholder: "Search Comics" %>
  <%= form.submit 'Find Comics' %>
<% end %>

<h2>Search Results</h2>

<% if @comics.present? %>
  <ul>
    <% @comics.each do |comic| %>
      <li>
        <% if comic.image_url.present? %>
          <%= image_tag comic.image_url %>
        <% else %>
          <p>No image available</p>
        <% end %>
        <div>
          <strong><%= comic.title %></strong> - <%= comic.issue %> - <%= comic.publisher %>
          <form action="<%= add_to_collection_comic_path(user_id: current_user.id, id: comic.id) %>" method="post">
            <%= button_to 'Add to Collection', add_to_collection_comic_path(id: comic.id), method: :post %>
          </form>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollectIt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
   
     <%= button_to 'Home', '/welcome' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div id="flash-messages">
        <%= msg %>
      </div>
    <% end %>
    <h1 style="text-align:center;"><span class="highlight">Collect It</span></h1>
 
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>User#index</h1>

app/views/users/login_form.html.erb
<h1>Existing Collect It Users Log In</h1>
<%= form_with url: login_path, method: :post, local: true do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %><br><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br><br>
  <%= f.submit "Log In" %>
<% end %>

app/views/users/new.html.erb
<h2>Register a New User</h2>
<%= form_with url: users_path, method: :post, local: true do |f| %>
  <%= f.label :username, "Username:" %><br>
  <%= f.text_field :username %><br><br>
  <%= f.label :email, "Email:" %><br>
  <%= f.text_field :email %><br><br>
  <%= f.label :password, "Password:" %><br>
  <%= f.text_field :password %><br><br>
  <%= f.label :password, "Confirm Password:" %><br>
  <%= f.text_field :password_confirmation %><br><br>
  <%= f.submit "Create New User" %>
<% end %>

app/views/users/show.html.erb
<h2 style="text-align:center;"><span class="highlight">Welcome to <%= current_user.username %> Collect It Dashboard</span></h2>
<% if current_user %>
  <%= form_with url: user_dashboard_search_path(@user), method: :get, local: true do |form| %>
    <%= form.text_field :query, placeholder: "Search Comics" %>
    <%= form.submit 'Find Comics' %>
  <% end %>
  <%= link_to 'Log Out', logout_path, method: :post %>
<% end %>

app/views/welcome/index.html.erb
<html>
<head>
<style>
div { 
  background-color: lightgrey;
  width: 500px;
  border: 50px solid orange;
  padding: 20px;
  margin: auto;
}
</style>
</head>
<body>
<center>
<div>
<h4>Welcome to Collect It</h4>
</div>
</center>


  <%= button_to "Create A New User", register_path, method: :get %>
  <%= button_to "Log In", "/login" %>

</html>